version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: amigo-secreto-php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - amigo_secreto_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: amigo-secreto-db
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amigo_secreto
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - amigo_secreto_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: amigo-secreto-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - amigo_secreto_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Painel Web
      - "1025:1025"  # Porta SMTP
    networks:
      - amigo_secreto_network

networks:
  amigo_secreto_network:
    driver: bridge
